<?php

namespace Database\Seeders\Common;

use App\Models\Common\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_alpha_2' => 'AF', 'iso_alpha_3' => 'AFG', 'iso_numeric' => '004', 'calling_code' => '+93'],
            ['name' => 'Albania', 'iso_alpha_2' => 'AL', 'iso_alpha_3' => 'ALB', 'iso_numeric' => '008', 'calling_code' => '+355'],
            ['name' => 'Algeria', 'iso_alpha_2' => 'DZ', 'iso_alpha_3' => 'DZA', 'iso_numeric' => '012', 'calling_code' => '+213'],
            ['name' => 'Andorra', 'iso_alpha_2' => 'AD', 'iso_alpha_3' => 'AND', 'iso_numeric' => '020', 'calling_code' => '+376'],
            ['name' => 'Angola', 'iso_alpha_2' => 'AO', 'iso_alpha_3' => 'AGO', 'iso_numeric' => '024', 'calling_code' => '+244'],
            ['name' => 'Antigua and Barbuda', 'iso_alpha_2' => 'AG', 'iso_alpha_3' => 'ATG', 'iso_numeric' => '028', 'calling_code' => '+1'],
            ['name' => 'Argentina', 'iso_alpha_2' => 'AR', 'iso_alpha_3' => 'ARG', 'iso_numeric' => '032', 'calling_code' => '+54'],
            ['name' => 'Armenia', 'iso_alpha_2' => 'AM', 'iso_alpha_3' => 'ARM', 'iso_numeric' => '051', 'calling_code' => '+374'],
            ['name' => 'Australia', 'iso_alpha_2' => 'AU', 'iso_alpha_3' => 'AUS', 'iso_numeric' => '036', 'calling_code' => '+61'],
            ['name' => 'Austria', 'iso_alpha_2' => 'AT', 'iso_alpha_3' => 'AUT', 'iso_numeric' => '040', 'calling_code' => '+43'],
            ['name' => 'Azerbaijan', 'iso_alpha_2' => 'AZ', 'iso_alpha_3' => 'AZE', 'iso_numeric' => '031', 'calling_code' => '+994'],
            ['name' => 'Bahamas', 'iso_alpha_2' => 'BS', 'iso_alpha_3' => 'BHS', 'iso_numeric' => '044', 'calling_code' => '+1'],
            ['name' => 'Bahrain', 'iso_alpha_2' => 'BH', 'iso_alpha_3' => 'BHR', 'iso_numeric' => '048', 'calling_code' => '+973'],
            ['name' => 'Bangladesh', 'iso_alpha_2' => 'BD', 'iso_alpha_3' => 'BGD', 'iso_numeric' => '050', 'calling_code' => '+880'],
            ['name' => 'Barbados', 'iso_alpha_2' => 'BB', 'iso_alpha_3' => 'BRB', 'iso_numeric' => '052', 'calling_code' => '+1'],
            ['name' => 'Belarus', 'iso_alpha_2' => 'BY', 'iso_alpha_3' => 'BLR', 'iso_numeric' => '112', 'calling_code' => '+375'],
            ['name' => 'Belgium', 'iso_alpha_2' => 'BE', 'iso_alpha_3' => 'BEL', 'iso_numeric' => '056', 'calling_code' => '+32'],
            ['name' => 'Belize', 'iso_alpha_2' => 'BZ', 'iso_alpha_3' => 'BLZ', 'iso_numeric' => '084', 'calling_code' => '+501'],
            ['name' => 'Benin', 'iso_alpha_2' => 'BJ', 'iso_alpha_3' => 'BEN', 'iso_numeric' => '204', 'calling_code' => '+229'],
            ['name' => 'Bhutan', 'iso_alpha_2' => 'BT', 'iso_alpha_3' => 'BTN', 'iso_numeric' => '064', 'calling_code' => '+975'],
            ['name' => 'Bolivia (Plurinational State of)', 'iso_alpha_2' => 'BO', 'iso_alpha_3' => 'BOL', 'iso_numeric' => '068', 'calling_code' => '+591'],
            ['name' => 'Bosnia and Herzegovina', 'iso_alpha_2' => 'BA', 'iso_alpha_3' => 'BIH', 'iso_numeric' => '070', 'calling_code' => '+387'],
            ['name' => 'Botswana', 'iso_alpha_2' => 'BW', 'iso_alpha_3' => 'BWA', 'iso_numeric' => '072', 'calling_code' => '+267'],
            ['name' => 'Brazil', 'iso_alpha_2' => 'BR', 'iso_alpha_3' => 'BRA', 'iso_numeric' => '076', 'calling_code' => '+55'],
            ['name' => 'Brunei Darussalam', 'iso_alpha_2' => 'BN', 'iso_alpha_3' => 'BRN', 'iso_numeric' => '096', 'calling_code' => '+673'],
            ['name' => 'Bulgaria', 'iso_alpha_2' => 'BG', 'iso_alpha_3' => 'BGR', 'iso_numeric' => '100', 'calling_code' => '+359'],
            ['name' => 'Burkina Faso', 'iso_alpha_2' => 'BF', 'iso_alpha_3' => 'BFA', 'iso_numeric' => '854', 'calling_code' => '+226'],
            ['name' => 'Burundi', 'iso_alpha_2' => 'BI', 'iso_alpha_3' => 'BDI', 'iso_numeric' => '108', 'calling_code' => '+257'],
            ['name' => 'Cabo Verde', 'iso_alpha_2' => 'CV', 'iso_alpha_3' => 'CPV', 'iso_numeric' => '132', 'calling_code' => '+238'],
            ['name' => 'Cambodia', 'iso_alpha_2' => 'KH', 'iso_alpha_3' => 'KHM', 'iso_numeric' => '116', 'calling_code' => '+855'],
            ['name' => 'Cameroon', 'iso_alpha_2' => 'CM', 'iso_alpha_3' => 'CMR', 'iso_numeric' => '120', 'calling_code' => '+237'],
            ['name' => 'Canada', 'iso_alpha_2' => 'CA', 'iso_alpha_3' => 'CAN', 'iso_numeric' => '124', 'calling_code' => '+1'],
            ['name' => 'Central African Republic', 'iso_alpha_2' => 'CF', 'iso_alpha_3' => 'CAF', 'iso_numeric' => '140', 'calling_code' => '+236'],
            ['name' => 'Chad', 'iso_alpha_2' => 'TD', 'iso_alpha_3' => 'TCD', 'iso_numeric' => '148', 'calling_code' => '+235'],
            ['name' => 'Chile', 'iso_alpha_2' => 'CL', 'iso_alpha_3' => 'CHL', 'iso_numeric' => '152', 'calling_code' => '+56'],
            ['name' => 'China', 'iso_alpha_2' => 'CN', 'iso_alpha_3' => 'CHN', 'iso_numeric' => '156', 'calling_code' => '+86'],
            ['name' => 'Colombia', 'iso_alpha_2' => 'CO', 'iso_alpha_3' => 'COL', 'iso_numeric' => '170', 'calling_code' => '+57'],
            ['name' => 'Comoros', 'iso_alpha_2' => 'KM', 'iso_alpha_3' => 'COM', 'iso_numeric' => '174', 'calling_code' => '+269'],
            ['name' => 'Congo', 'iso_alpha_2' => 'CG', 'iso_alpha_3' => 'COG', 'iso_numeric' => '178', 'calling_code' => '+242'],
            ['name' => 'Congo, Democratic Republic of the', 'iso_alpha_2' => 'CD', 'iso_alpha_3' => 'COD', 'iso_numeric' => '180', 'calling_code' => '+243'],
            ['name' => 'Costa Rica', 'iso_alpha_2' => 'CR', 'iso_alpha_3' => 'CRI', 'iso_numeric' => '188', 'calling_code' => '+506'],
            ['name' => 'Croatia', 'iso_alpha_2' => 'HR', 'iso_alpha_3' => 'HRV', 'iso_numeric' => '191', 'calling_code' => '+385'],
            ['name' => 'Cuba', 'iso_alpha_2' => 'CU', 'iso_alpha_3' => 'CUB', 'iso_numeric' => '192', 'calling_code' => '+53'],
            ['name' => 'Cyprus', 'iso_alpha_2' => 'CY', 'iso_alpha_3' => 'CYP', 'iso_numeric' => '196', 'calling_code' => '+357'],
            ['name' => 'Czechia', 'iso_alpha_2' => 'CZ', 'iso_alpha_3' => 'CZE', 'iso_numeric' => '203', 'calling_code' => '+420'],
            ['name' => 'Denmark', 'iso_alpha_2' => 'DK', 'iso_alpha_3' => 'DNK', 'iso_numeric' => '208', 'calling_code' => '+45'],
            ['name' => 'Djibouti', 'iso_alpha_2' => 'DJ', 'iso_alpha_3' => 'DJI', 'iso_numeric' => '262', 'calling_code' => '+253'],
            ['name' => 'Dominica', 'iso_alpha_2' => 'DM', 'iso_alpha_3' => 'DMA', 'iso_numeric' => '212', 'calling_code' => '+1'],
            ['name' => 'Dominican Republic', 'iso_alpha_2' => 'DO', 'iso_alpha_3' => 'DOM', 'iso_numeric' => '214', 'calling_code' => '+1'],
            ['name' => 'Ecuador', 'iso_alpha_2' => 'EC', 'iso_alpha_3' => 'ECU', 'iso_numeric' => '218', 'calling_code' => '+593'],
            ['name' => 'Egypt', 'iso_alpha_2' => 'EG', 'iso_alpha_3' => 'EGY', 'iso_numeric' => '818', 'calling_code' => '+20'],
            ['name' => 'El Salvador', 'iso_alpha_2' => 'SV', 'iso_alpha_3' => 'SLV', 'iso_numeric' => '222', 'calling_code' => '+503'],
            ['name' => 'Equatorial Guinea', 'iso_alpha_2' => 'GQ', 'iso_alpha_3' => 'GNQ', 'iso_numeric' => '226', 'calling_code' => '+240'],
            ['name' => 'Eritrea', 'iso_alpha_2' => 'ER', 'iso_alpha_3' => 'ERI', 'iso_numeric' => '232', 'calling_code' => '+291'],
            ['name' => 'Estonia', 'iso_alpha_2' => 'EE', 'iso_alpha_3' => 'EST', 'iso_numeric' => '233', 'calling_code' => '+372'],
            ['name' => 'Eswatini', 'iso_alpha_2' => 'SZ', 'iso_alpha_3' => 'SWZ', 'iso_numeric' => '748', 'calling_code' => '+268'],
            ['name' => 'Ethiopia', 'iso_alpha_2' => 'ET', 'iso_alpha_3' => 'ETH', 'iso_numeric' => '231', 'calling_code' => '+251'],
            ['name' => 'Fiji', 'iso_alpha_2' => 'FJ', 'iso_alpha_3' => 'FJI', 'iso_numeric' => '242', 'calling_code' => '+679'],
            ['name' => 'Finland', 'iso_alpha_2' => 'FI', 'iso_alpha_3' => 'FIN', 'iso_numeric' => '246', 'calling_code' => '+358'],
            ['name' => 'France', 'iso_alpha_2' => 'FR', 'iso_alpha_3' => 'FRA', 'iso_numeric' => '250', 'calling_code' => '+33'],
            ['name' => 'Gabon', 'iso_alpha_2' => 'GA', 'iso_alpha_3' => 'GAB', 'iso_numeric' => '266', 'calling_code' => '+241'],
            ['name' => 'Indonesia', 'iso_alpha_2' => 'ID', 'iso_alpha_3' => 'IDN', 'iso_numeric' => '360', 'calling_code' => '+62'],
            ['name' => 'Gambia', 'iso_alpha_2' => 'GM', 'iso_alpha_3' => 'GMB', 'iso_numeric' => '270', 'calling_code' => '+220'],
            ['name' => 'Georgia', 'iso_alpha_2' => 'GE', 'iso_alpha_3' => 'GEO', 'iso_numeric' => '268', 'calling_code' => '+995'],
            ['name' => 'Germany', 'iso_alpha_2' => 'DE', 'iso_alpha_3' => 'DEU', 'iso_numeric' => '276', 'calling_code' => '+49'],
            ['name' => 'Ghana', 'iso_alpha_2' => 'GH', 'iso_alpha_3' => 'GHA', 'iso_numeric' => '288', 'calling_code' => '+233'],
            ['name' => 'Greece', 'iso_alpha_2' => 'GR', 'iso_alpha_3' => 'GRC', 'iso_numeric' => '300', 'calling_code' => '+30'],
            ['name' => 'Grenada', 'iso_alpha_2' => 'GD', 'iso_alpha_3' => 'GRD', 'iso_numeric' => '308', 'calling_code' => '+1'],
            ['name' => 'Guatemala', 'iso_alpha_2' => 'GT', 'iso_alpha_3' => 'GTM', 'iso_numeric' => '320', 'calling_code' => '+502'],
            ['name' => 'Guinea', 'iso_alpha_2' => 'GN', 'iso_alpha_3' => 'GIN', 'iso_numeric' => '324', 'calling_code' => '+224'],
            ['name' => 'Guinea-Bissau', 'iso_alpha_2' => 'GW', 'iso_alpha_3' => 'GNB', 'iso_numeric' => '624', 'calling_code' => '+245'],
            ['name' => 'Guyana', 'iso_alpha_2' => 'GY', 'iso_alpha_3' => 'GUY', 'iso_numeric' => '328', 'calling_code' => '+592'],
            ['name' => 'Haiti', 'iso_alpha_2' => 'HT', 'iso_alpha_3' => 'HTI', 'iso_numeric' => '332', 'calling_code' => '+509'],
            ['name' => 'Honduras', 'iso_alpha_2' => 'HN', 'iso_alpha_3' => 'HND', 'iso_numeric' => '340', 'calling_code' => '+504'],
            ['name' => 'Hungary', 'iso_alpha_2' => 'HU', 'iso_alpha_3' => 'HUN', 'iso_numeric' => '348', 'calling_code' => '+36'],
            ['name' => 'Iceland', 'iso_alpha_2' => 'IS', 'iso_alpha_3' => 'ISL', 'iso_numeric' => '352', 'calling_code' => '+354'],
            ['name' => 'India', 'iso_alpha_2' => 'IN', 'iso_alpha_3' => 'IND', 'iso_numeric' => '356', 'calling_code' => '+91'],
            ['name' => 'Iran (Islamic Republic of)', 'iso_alpha_2' => 'IR', 'iso_alpha_3' => 'IRN', 'iso_numeric' => '364', 'calling_code' => '+98'],
            ['name' => 'Iraq', 'iso_alpha_2' => 'IQ', 'iso_alpha_3' => 'IRQ', 'iso_numeric' => '368', 'calling_code' => '+964'],
            ['name' => 'Ireland', 'iso_alpha_2' => 'IE', 'iso_alpha_3' => 'IRL', 'iso_numeric' => '372', 'calling_code' => '+353'],
            ['name' => 'Israel', 'iso_alpha_2' => 'IL', 'iso_alpha_3' => 'ISR', 'iso_numeric' => '376', 'calling_code' => '+972'],
            ['name' => 'Italy', 'iso_alpha_2' => 'IT', 'iso_alpha_3' => 'ITA', 'iso_numeric' => '380', 'calling_code' => '+39'],
            ['name' => 'Jamaica', 'iso_alpha_2' => 'JM', 'iso_alpha_3' => 'JAM', 'iso_numeric' => '388', 'calling_code' => '+1'],
            ['name' => 'Japan', 'iso_alpha_2' => 'JP', 'iso_alpha_3' => 'JPN', 'iso_numeric' => '392', 'calling_code' => '+81'],
            ['name' => 'Jordan', 'iso_alpha_2' => 'JO', 'iso_alpha_3' => 'JOR', 'iso_numeric' => '400', 'calling_code' => '+962'],
            ['name' => 'Kazakhstan', 'iso_alpha_2' => 'KZ', 'iso_alpha_3' => 'KAZ', 'iso_numeric' => '398', 'calling_code' => '+7'],
            ['name' => 'Kenya', 'iso_alpha_2' => 'KE', 'iso_alpha_3' => 'KEN', 'iso_numeric' => '404', 'calling_code' => '+254'],
            ['name' => 'Kiribati', 'iso_alpha_2' => 'KI', 'iso_alpha_3' => 'KIR', 'iso_numeric' => '296', 'calling_code' => '+686'],
            ['name' => 'Korea (Democratic People\'s Republic of)', 'iso_alpha_2' => 'KP', 'iso_alpha_3' => 'PRK', 'iso_numeric' => '408', 'calling_code' => '+850'],
            ['name' => 'Korea, Republic of', 'iso_alpha_2' => 'KR', 'iso_alpha_3' => 'KOR', 'iso_numeric' => '410', 'calling_code' => '+82'],
            ['name' => 'Kuwait', 'iso_alpha_2' => 'KW', 'iso_alpha_3' => 'KWT', 'iso_numeric' => '414', 'calling_code' => '+965'],
            ['name' => 'Kyrgyzstan', 'iso_alpha_2' => 'KG', 'iso_alpha_3' => 'KGZ', 'iso_numeric' => '417', 'calling_code' => '+996'],
            ['name' => 'Lao People\'s Democratic Republic', 'iso_alpha_2' => 'LA', 'iso_alpha_3' => 'LAO', 'iso_numeric' => '418', 'calling_code' => '+856'],
            ['name' => 'Latvia', 'iso_alpha_2' => 'LV', 'iso_alpha_3' => 'LVA', 'iso_numeric' => '428', 'calling_code' => '+371'],
            ['name' => 'Lebanon', 'iso_alpha_2' => 'LB', 'iso_alpha_3' => 'LBN', 'iso_numeric' => '422', 'calling_code' => '+961'],
            ['name' => 'Lesotho', 'iso_alpha_2' => 'LS', 'iso_alpha_3' => 'LSO', 'iso_numeric' => '426', 'calling_code' => '+266'],
            ['name' => 'Liberia', 'iso_alpha_2' => 'LR', 'iso_alpha_3' => 'LBR', 'iso_numeric' => '430', 'calling_code' => '+231'],
            ['name' => 'Libya', 'iso_alpha_2' => 'LY', 'iso_alpha_3' => 'LBY', 'iso_numeric' => '434', 'calling_code' => '+218'],
            ['name' => 'Liechtenstein', 'iso_alpha_2' => 'LI', 'iso_alpha_3' => 'LIE', 'iso_numeric' => '438', 'calling_code' => '+423'],
            ['name' => 'Lithuania', 'iso_alpha_2' => 'LT', 'iso_alpha_3' => 'LTU', 'iso_numeric' => '440', 'calling_code' => '+370'],
            ['name' => 'Luxembourg', 'iso_alpha_2' => 'LU', 'iso_alpha_3' => 'LUX', 'iso_numeric' => '442', 'calling_code' => '+352'],
            ['name' => 'Madagascar', 'iso_alpha_2' => 'MG', 'iso_alpha_3' => 'MDG', 'iso_numeric' => '450', 'calling_code' => '+261'],
            ['name' => 'Malawi', 'iso_alpha_2' => 'MW', 'iso_alpha_3' => 'MWI', 'iso_numeric' => '454', 'calling_code' => '+265'],
            ['name' => 'Malaysia', 'iso_alpha_2' => 'MY', 'iso_alpha_3' => 'MYS', 'iso_numeric' => '458', 'calling_code' => '+60'],
            ['name' => 'Maldives', 'iso_alpha_2' => 'MV', 'iso_alpha_3' => 'MDV', 'iso_numeric' => '462', 'calling_code' => '+960'],
            ['name' => 'Mali', 'iso_alpha_2' => 'ML', 'iso_alpha_3' => 'MLI', 'iso_numeric' => '466', 'calling_code' => '+223'],
            ['name' => 'Malta', 'iso_alpha_2' => 'MT', 'iso_alpha_3' => 'MLT', 'iso_numeric' => '470', 'calling_code' => '+356'],
            ['name' => 'Marshall Islands', 'iso_alpha_2' => 'MH', 'iso_alpha_3' => 'MHL', 'iso_numeric' => '584', 'calling_code' => '+692'],
            ['name' => 'Mauritania', 'iso_alpha_2' => 'MR', 'iso_alpha_3' => 'MRT', 'iso_numeric' => '478', 'calling_code' => '+222'],
            ['name' => 'Mauritius', 'iso_alpha_2' => 'MU', 'iso_alpha_3' => 'MUS', 'iso_numeric' => '480', 'calling_code' => '+230'],
            ['name' => 'Mexico', 'iso_alpha_2' => 'MX', 'iso_alpha_3' => 'MEX', 'iso_numeric' => '484', 'calling_code' => '+52'],
            ['name' => 'Micronesia (Federated States of)', 'iso_alpha_2' => 'FM', 'iso_alpha_3' => 'FSM', 'iso_numeric' => '583', 'calling_code' => '+691'],
            ['name' => 'Moldova, Republic of', 'iso_alpha_2' => 'MD', 'iso_alpha_3' => 'MDA', 'iso_numeric' => '498', 'calling_code' => '+373'],
            ['name' => 'Monaco', 'iso_alpha_2' => 'MC', 'iso_alpha_3' => 'MCO', 'iso_numeric' => '492', 'calling_code' => '+377'],
            ['name' => 'Mongolia', 'iso_alpha_2' => 'MN', 'iso_alpha_3' => 'MNG', 'iso_numeric' => '496', 'calling_code' => '+976'],
            ['name' => 'Montenegro', 'iso_alpha_2' => 'ME', 'iso_alpha_3' => 'MNE', 'iso_numeric' => '499', 'calling_code' => '+382'],
            ['name' => 'Morocco', 'iso_alpha_2' => 'MA', 'iso_alpha_3' => 'MAR', 'iso_numeric' => '504', 'calling_code' => '+212'],
            ['name' => 'Mozambique', 'iso_alpha_2' => 'MZ', 'iso_alpha_3' => 'MOZ', 'iso_numeric' => '508', 'calling_code' => '+258'],
            ['name' => 'Myanmar', 'iso_alpha_2' => 'MM', 'iso_alpha_3' => 'MMR', 'iso_numeric' => '104', 'calling_code' => '+95'],
            ['name' => 'Namibia', 'iso_alpha_2' => 'NA', 'iso_alpha_3' => 'NAM', 'iso_numeric' => '516', 'calling_code' => '+264'],
            ['name' => 'Nauru', 'iso_alpha_2' => 'NR', 'iso_alpha_3' => 'NRU', 'iso_numeric' => '520', 'calling_code' => '+674'],
            ['name' => 'Nepal', 'iso_alpha_2' => 'NP', 'iso_alpha_3' => 'NPL', 'iso_numeric' => '524', 'calling_code' => '+977'],
            ['name' => 'Netherlands', 'iso_alpha_2' => 'NL', 'iso_alpha_3' => 'NLD', 'iso_numeric' => '528', 'calling_code' => '+31'],
            ['name' => 'New Zealand', 'iso_alpha_2' => 'NZ', 'iso_alpha_3' => 'NZL', 'iso_numeric' => '554', 'calling_code' => '+64'],
            ['name' => 'Nicaragua', 'iso_alpha_2' => 'NI', 'iso_alpha_3' => 'NIC', 'iso_numeric' => '558', 'calling_code' => '+505'],
            ['name' => 'Niger', 'iso_alpha_2' => 'NE', 'iso_alpha_3' => 'NER', 'iso_numeric' => '562', 'calling_code' => '+227'],
            ['name' => 'Nigeria', 'iso_alpha_2' => 'NG', 'iso_alpha_3' => 'NGA', 'iso_numeric' => '566', 'calling_code' => '+234'],
            ['name' => 'North Macedonia', 'iso_alpha_2' => 'MK', 'iso_alpha_3' => 'MKD', 'iso_numeric' => '807', 'calling_code' => '+389'],
            ['name' => 'Norway', 'iso_alpha_2' => 'NO', 'iso_alpha_3' => 'NOR', 'iso_numeric' => '578', 'calling_code' => '+47'],
            ['name' => 'Oman', 'iso_alpha_2' => 'OM', 'iso_alpha_3' => 'OMN', 'iso_numeric' => '512', 'calling_code' => '+968'],
            ['name' => 'Pakistan', 'iso_alpha_2' => 'PK', 'iso_alpha_3' => 'PAK', 'iso_numeric' => '586', 'calling_code' => '+92'],
            ['name' => 'Palau', 'iso_alpha_2' => 'PW', 'iso_alpha_3' => 'PLW', 'iso_numeric' => '585', 'calling_code' => '+680'],
            ['name' => 'Panama', 'iso_alpha_2' => 'PA', 'iso_alpha_3' => 'PAN', 'iso_numeric' => '591', 'calling_code' => '+507'],
            ['name' => 'Papua New Guinea', 'iso_alpha_2' => 'PG', 'iso_alpha_3' => 'PNG', 'iso_numeric' => '598', 'calling_code' => '+675'],
            ['name' => 'Paraguay', 'iso_alpha_2' => 'PY', 'iso_alpha_3' => 'PRY', 'iso_numeric' => '600', 'calling_code' => '+595'],
            ['name' => 'Peru', 'iso_alpha_2' => 'PE', 'iso_alpha_3' => 'PER', 'iso_numeric' => '604', 'calling_code' => '+51'],
            ['name' => 'Philippines', 'iso_alpha_2' => 'PH', 'iso_alpha_3' => 'PHL', 'iso_numeric' => '608', 'calling_code' => '+63'],
            ['name' => 'Poland', 'iso_alpha_2' => 'PL', 'iso_alpha_3' => 'POL', 'iso_numeric' => '616', 'calling_code' => '+48'],
            ['name' => 'Portugal', 'iso_alpha_2' => 'PT', 'iso_alpha_3' => 'PRT', 'iso_numeric' => '620', 'calling_code' => '+351'],
            ['name' => 'Qatar', 'iso_alpha_2' => 'QA', 'iso_alpha_3' => 'QAT', 'iso_numeric' => '634', 'calling_code' => '+974'],
            ['name' => 'Romania', 'iso_alpha_2' => 'RO', 'iso_alpha_3' => 'ROU', 'iso_numeric' => '642', 'calling_code' => '+40'],
            ['name' => 'Russian Federation', 'iso_alpha_2' => 'RU', 'iso_alpha_3' => 'RUS', 'iso_numeric' => '643', 'calling_code' => '+7'],
            ['name' => 'Rwanda', 'iso_alpha_2' => 'RW', 'iso_alpha_3' => 'RWA', 'iso_numeric' => '646', 'calling_code' => '+250'],
            ['name' => 'Saint Kitts and Nevis', 'iso_alpha_2' => 'KN', 'iso_alpha_3' => 'KNA', 'iso_numeric' => '659', 'calling_code' => '+1'],
            ['name' => 'Saint Lucia', 'iso_alpha_2' => 'LC', 'iso_alpha_3' => 'LCA', 'iso_numeric' => '662', 'calling_code' => '+1'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_alpha_2' => 'VC', 'iso_alpha_3' => 'VCT', 'iso_numeric' => '670', 'calling_code' => '+1'],
            ['name' => 'Samoa', 'iso_alpha_2' => 'WS', 'iso_alpha_3' => 'WSM', 'iso_numeric' => '882', 'calling_code' => '+685'],
            ['name' => 'San Marino', 'iso_alpha_2' => 'SM', 'iso_alpha_3' => 'SMR', 'iso_numeric' => '674', 'calling_code' => '+378'],
            ['name' => 'Sao Tome and Principe', 'iso_alpha_2' => 'ST', 'iso_alpha_3' => 'STP', 'iso_numeric' => '678', 'calling_code' => '+239'],
            ['name' => 'Saudi Arabia', 'iso_alpha_2' => 'SA', 'iso_alpha_3' => 'SAU', 'iso_numeric' => '682', 'calling_code' => '+966'],
            ['name' => 'Senegal', 'iso_alpha_2' => 'SN', 'iso_alpha_3' => 'SEN', 'iso_numeric' => '686', 'calling_code' => '+221'],
            ['name' => 'Serbia', 'iso_alpha_2' => 'RS', 'iso_alpha_3' => 'SRB', 'iso_numeric' => '688', 'calling_code' => '+381'],
            ['name' => 'Seychelles', 'iso_alpha_2' => 'SC', 'iso_alpha_3' => 'SYC', 'iso_numeric' => '690', 'calling_code' => '+248'],
            ['name' => 'Sierra Leone', 'iso_alpha_2' => 'SL', 'iso_alpha_3' => 'SLE', 'iso_numeric' => '694', 'calling_code' => '+232'],
            ['name' => 'Singapore', 'iso_alpha_2' => 'SG', 'iso_alpha_3' => 'SGP', 'iso_numeric' => '702', 'calling_code' => '+65'],
            ['name' => 'Slovakia', 'iso_alpha_2' => 'SK', 'iso_alpha_3' => 'SVK', 'iso_numeric' => '703', 'calling_code' => '+421'],
            ['name' => 'Slovenia', 'iso_alpha_2' => 'SI', 'iso_alpha_3' => 'SVN', 'iso_numeric' => '705', 'calling_code' => '+386'],
            ['name' => 'Solomon Islands', 'iso_alpha_2' => 'SB', 'iso_alpha_3' => 'SLB', 'iso_numeric' => '090', 'calling_code' => '+677'],
            ['name' => 'Somalia', 'iso_alpha_2' => 'SO', 'iso_alpha_3' => 'SOM', 'iso_numeric' => '706', 'calling_code' => '+252'],
            ['name' => 'South Africa', 'iso_alpha_2' => 'ZA', 'iso_alpha_3' => 'ZAF', 'iso_numeric' => '710', 'calling_code' => '+27'],
            ['name' => 'South Sudan', 'iso_alpha_2' => 'SS', 'iso_alpha_3' => 'SSD', 'iso_numeric' => '728', 'calling_code' => '+211'],
            ['name' => 'Spain', 'iso_alpha_2' => 'ES', 'iso_alpha_3' => 'ESP', 'iso_numeric' => '724', 'calling_code' => '+34'],
            ['name' => 'Sri Lanka', 'iso_alpha_2' => 'LK', 'iso_alpha_3' => 'LKA', 'iso_numeric' => '144', 'calling_code' => '+94'],
            ['name' => 'Sudan', 'iso_alpha_2' => 'SD', 'iso_alpha_3' => 'SDN', 'iso_numeric' => '729', 'calling_code' => '+249'],
            ['name' => 'Suriname', 'iso_alpha_2' => 'SR', 'iso_alpha_3' => 'SUR', 'iso_numeric' => '740', 'calling_code' => '+597'],
            ['name' => 'Sweden', 'iso_alpha_2' => 'SE', 'iso_alpha_3' => 'SWE', 'iso_numeric' => '752', 'calling_code' => '+46'],
            ['name' => 'Switzerland', 'iso_alpha_2' => 'CH', 'iso_alpha_3' => 'CHE', 'iso_numeric' => '756', 'calling_code' => '+41'],
            ['name' => 'Syrian Arab Republic', 'iso_alpha_2' => 'SY', 'iso_alpha_3' => 'SYR', 'iso_numeric' => '760', 'calling_code' => '+963'],
            ['name' => 'Tajikistan', 'iso_alpha_2' => 'TJ', 'iso_alpha_3' => 'TJK', 'iso_numeric' => '762', 'calling_code' => '+992'],
            ['name' => 'Tanzania, United Republic of', 'iso_alpha_2' => 'TZ', 'iso_alpha_3' => 'TZA', 'iso_numeric' => '834', 'calling_code' => '+255'],
            ['name' => 'Thailand', 'iso_alpha_2' => 'TH', 'iso_alpha_3' => 'THA', 'iso_numeric' => '764', 'calling_code' => '+66'],
            ['name' => 'Timor-Leste', 'iso_alpha_2' => 'TL', 'iso_alpha_3' => 'TLS', 'iso_numeric' => '626', 'calling_code' => '+670'],
            ['name' => 'Togo', 'iso_alpha_2' => 'TG', 'iso_alpha_3' => 'TGO', 'iso_numeric' => '768', 'calling_code' => '+228'],
            ['name' => 'Tonga', 'iso_alpha_2' => 'TO', 'iso_alpha_3' => 'TON', 'iso_numeric' => '776', 'calling_code' => '+676'],
            ['name' => 'Trinidad and Tobago', 'iso_alpha_2' => 'TT', 'iso_alpha_3' => 'TTO', 'iso_numeric' => '780', 'calling_code' => '+1'],
            ['name' => 'Tunisia', 'iso_alpha_2' => 'TN', 'iso_alpha_3' => 'TUN', 'iso_numeric' => '788', 'calling_code' => '+216'],
            ['name' => 'Turkey', 'iso_alpha_2' => 'TR', 'iso_alpha_3' => 'TUR', 'iso_numeric' => '792', 'calling_code' => '+90'],
            ['name' => 'Turkmenistan', 'iso_alpha_2' => 'TM', 'iso_alpha_3' => 'TKM', 'iso_numeric' => '795', 'calling_code' => '+993'],
            ['name' => 'Tuvalu', 'iso_alpha_2' => 'TV', 'iso_alpha_3' => 'TUV', 'iso_numeric' => '798', 'calling_code' => '+688'],
            ['name' => 'Uganda', 'iso_alpha_2' => 'UG', 'iso_alpha_3' => 'UGA', 'iso_numeric' => '800', 'calling_code' => '+256'],
            ['name' => 'Ukraine', 'iso_alpha_2' => 'UA', 'iso_alpha_3' => 'UKR', 'iso_numeric' => '804', 'calling_code' => '+380'],
            ['name' => 'United Arab Emirates', 'iso_alpha_2' => 'AE', 'iso_alpha_3' => 'ARE', 'iso_numeric' => '784', 'calling_code' => '+971'],
            ['name' => 'United Kingdom', 'iso_alpha_2' => 'GB', 'iso_alpha_3' => 'GBR', 'iso_numeric' => '826', 'calling_code' => '+44'],
            ['name' => 'United States of America', 'iso_alpha_2' => 'US', 'iso_alpha_3' => 'USA', 'iso_numeric' => '840', 'calling_code' => '+1'],
            ['name' => 'Uruguay', 'iso_alpha_2' => 'UY', 'iso_alpha_3' => 'URY', 'iso_numeric' => '858', 'calling_code' => '+598'],
            ['name' => 'Uzbekistan', 'iso_alpha_2' => 'UZ', 'iso_alpha_3' => 'UZB', 'iso_numeric' => '860', 'calling_code' => '+998'],
            ['name' => 'Vanuatu', 'iso_alpha_2' => 'VU', 'iso_alpha_3' => 'VUT', 'iso_numeric' => '548', 'calling_code' => '+678'],
            ['name' => 'Venezuela (Bolivarian Republic of)', 'iso_alpha_2' => 'VE', 'iso_alpha_3' => 'VEN', 'iso_numeric' => '862', 'calling_code' => '+58'],
            ['name' => 'Viet Nam', 'iso_alpha_2' => 'VN', 'iso_alpha_3' => 'VNM', 'iso_numeric' => '704', 'calling_code' => '+84'],
            ['name' => 'Yemen', 'iso_alpha_2' => 'YE', 'iso_alpha_3' => 'YEM', 'iso_numeric' => '887', 'calling_code' => '+967'],
            ['name' => 'Zambia', 'iso_alpha_2' => 'ZM', 'iso_alpha_3' => 'ZMB', 'iso_numeric' => '894', 'calling_code' => '+260'],
            ['name' => 'Zimbabwe', 'iso_alpha_2' => 'ZW', 'iso_alpha_3' => 'ZWE', 'iso_numeric' => '716', 'calling_code' => '+263'],
            ['name' => 'Åland Islands', 'iso_alpha_2' => 'AX', 'iso_alpha_3' => 'ALA', 'iso_numeric' => '248', 'calling_code' => '+358'],
            ['name' => 'Antarctica', 'iso_alpha_2' => 'AQ', 'iso_alpha_3' => 'ATA', 'iso_numeric' => '10', 'calling_code' => '+672'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'iso_alpha_2' => 'BQ', 'iso_alpha_3' => 'BES', 'iso_numeric' => '535', 'calling_code' => '+599'],
            ['name' => 'Bouvet Island', 'iso_alpha_2' => 'BV', 'iso_alpha_3' => 'BVT', 'iso_numeric' => '74', 'calling_code' => ''],
            ['name' => 'Cocos (Keeling) Islands', 'iso_alpha_2' => 'CC', 'iso_alpha_3' => 'CCK', 'iso_numeric' => '166', 'calling_code' => '+61'],
            ['name' => 'Congo, Democratic Republic of the', 'iso_alpha_2' => 'CD', 'iso_alpha_3' => 'COD', 'iso_numeric' => '180', 'calling_code' => '+243'],
            ['name' => 'Curaçao', 'iso_alpha_2' => 'CW', 'iso_alpha_3' => 'CUW', 'iso_numeric' => '531', 'calling_code' => '+599'],
            ['name' => 'Guernsey', 'iso_alpha_2' => 'GG', 'iso_alpha_3' => 'GGY', 'iso_numeric' => '831', 'calling_code' => '+44'],
            ['name' => 'Heard Island and McDonald Islands', 'iso_alpha_2' => 'HM', 'iso_alpha_3' => 'HMD', 'iso_numeric' => '334', 'calling_code' => ''],
            ['name' => 'Holy See', 'iso_alpha_2' => 'VA', 'iso_alpha_3' => 'VAT', 'iso_numeric' => '336', 'calling_code' => '+379'],
            ['name' => 'Isle of Man', 'iso_alpha_2' => 'IM', 'iso_alpha_3' => 'IMN', 'iso_numeric' => '833', 'calling_code' => '+44'],
            ['name' => 'Jersey', 'iso_alpha_2' => 'JE', 'iso_alpha_3' => 'JEY', 'iso_numeric' => '832', 'calling_code' => '+44'],
            ['name' => 'Macao', 'iso_alpha_2' => 'MO', 'iso_alpha_3' => 'MAC', 'iso_numeric' => '446', 'calling_code' => '+853'],
            ['name' => 'Montserrat', 'iso_alpha_2' => 'MS', 'iso_alpha_3' => 'MSR', 'iso_numeric' => '500', 'calling_code' => '+1'],
            ['name' => 'Niue', 'iso_alpha_2' => 'NU', 'iso_alpha_3' => 'NIU', 'iso_numeric' => '570', 'calling_code' => '+683'],
            ['name' => 'Norfolk Island', 'iso_alpha_2' => 'NF', 'iso_alpha_3' => 'NFK', 'iso_numeric' => '574', 'calling_code' => '+672'],
            ['name' => 'Northern Mariana Islands', 'iso_alpha_2' => 'MP', 'iso_alpha_3' => 'MNP', 'iso_numeric' => '580', 'calling_code' => '+1'],
            ['name' => 'Palestine, State of', 'iso_alpha_2' => 'PS', 'iso_alpha_3' => 'PSE', 'iso_numeric' => '275', 'calling_code' => '+970'],
            ['name' => 'Pitcairn', 'iso_alpha_2' => 'PN', 'iso_alpha_3' => 'PCN', 'iso_numeric' => '612', 'calling_code' => '+64'],
            ['name' => 'Saint Barthélemy', 'iso_alpha_2' => 'BL', 'iso_alpha_3' => 'BLM', 'iso_numeric' => '652', 'calling_code' => '+590'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso_alpha_2' => 'SH', 'iso_alpha_3' => 'SHN', 'iso_numeric' => '654', 'calling_code' => '+290'],
            ['name' => 'Saint Martin (French part)', 'iso_alpha_2' => 'MF', 'iso_alpha_3' => 'MAF', 'iso_numeric' => '663', 'calling_code' => '+590'],
            ['name' => 'Saint Pierre and Miquelon', 'iso_alpha_2' => 'PM', 'iso_alpha_3' => 'SPM', 'iso_numeric' => '666', 'calling_code' => '+508'],
            ['name' => 'Sint Maarten (Dutch part)', 'iso_alpha_2' => 'SX', 'iso_alpha_3' => 'SXM', 'iso_numeric' => '534', 'calling_code' => '+1'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'iso_alpha_2' => 'GS', 'iso_alpha_3' => 'SGS', 'iso_numeric' => '239', 'calling_code' => ''],
            ['name' => 'South Sudan', 'iso_alpha_2' => 'SS', 'iso_alpha_3' => 'SSD', 'iso_numeric' => '728', 'calling_code' => '+211'],
            ['name' => 'Svalbard and Jan Mayen', 'iso_alpha_2' => 'SJ', 'iso_alpha_3' => 'SJM', 'iso_numeric' => '744', 'calling_code' => '+47'],
            ['name' => 'Tokelau', 'iso_alpha_2' => 'TK', 'iso_alpha_3' => 'TKL', 'iso_numeric' => '772', 'calling_code' => '+690'],
            ['name' => 'Turks and Caicos Islands', 'iso_alpha_2' => 'TC', 'iso_alpha_3' => 'TCA', 'iso_numeric' => '796', 'calling_code' => '+1'],
            ['name' => 'United States Minor Outlying Islands', 'iso_alpha_2' => 'UM', 'iso_alpha_3' => 'UMI', 'iso_numeric' => '581', 'calling_code' => ''],
            ['name' => 'Virgin Islands (British)', 'iso_alpha_2' => 'VG', 'iso_alpha_3' => 'VGB', 'iso_numeric' => '092', 'calling_code' => '+1'],
            ['name' => 'Virgin Islands (U.S.)', 'iso_alpha_2' => 'VI', 'iso_alpha_3' => 'VIR', 'iso_numeric' => '850', 'calling_code' => '+1'],
            ['name' => 'Wallis and Futuna', 'iso_alpha_2' => 'WF', 'iso_alpha_3' => 'WLF', 'iso_numeric' => '876', 'calling_code' => '+681'],
            ['name' => 'Western Sahara', 'iso_alpha_2' => 'EH', 'iso_alpha_3' => 'ESH', 'iso_numeric' => '732', 'calling_code' => '+212'],
            ['name' => 'United States Minor Outlying Islands', 'iso_alpha_2' => 'UM', 'iso_alpha_3' => 'UMI', 'iso_numeric' => '581', 'calling_code' => '']
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
